/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import CapaLogica.ClientesBL;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class ManagerShop extends javax.swing.JFrame {

    /**
     * Creates new form ManagerShop
     */
    public ManagerShop() {
        initComponents();
        this.setLocationRelativeTo(null);
        enabledHeader(jLabelClientes);
        enabledPanels(Clientes, OpcionesCliente, 0);
        getCurrentContentTable(0, false);
    }
    private boolean normalSize = true;
    private int x, y;
    private int TableActive = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenus = new javax.swing.JPanel();
        Clientes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        RRHH = new javax.swing.JPanel();
        Inventario = new javax.swing.JPanel();
        Reservacion = new javax.swing.JPanel();
        Historico = new javax.swing.JPanel();
        Disponibilidad = new javax.swing.JPanel();
        Session = new javax.swing.JPanel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelRRHH = new javax.swing.JLabel();
        jLabelInventario = new javax.swing.JLabel();
        jLabelReservacion = new javax.swing.JLabel();
        jLabelHistorico = new javax.swing.JLabel();
        jLabelDisponibilidad = new javax.swing.JLabel();
        jLabelSession = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        OpcionesCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ClienteNombre = new javax.swing.JTextField();
        ClientePrimerApellido = new javax.swing.JTextField();
        ClienteSegundoApellido = new javax.swing.JTextField();
        ClienteProfesion = new javax.swing.JTextField();
        ClienteGenero = new javax.swing.JComboBox();
        ClienteCedula = new javax.swing.JTextField();
        ClienteDireccion = new javax.swing.JTextField();
        ClienteEstado = new javax.swing.JCheckBox();
        ClienteCarnet = new javax.swing.JTextField();
        ClienteFechaNacimiento = new javax.swing.JFormattedTextField();
        ClienteEdad = new javax.swing.JLabel();
        OpcionesRRHH = new javax.swing.JPanel();
        OpcionesInventario = new javax.swing.JPanel();
        OpcionesReservacion = new javax.swing.JPanel();
        OpcionesHistorico = new javax.swing.JPanel();
        OpcionesDisponibilidad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jPanel9.setBackground(new java.awt.Color(0, 98, 175));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sistema de Administracion de Peliculas y empleados");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MAXIN-40-OUT.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MIN-40-OUT.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/CANCEL-GRANDE-OUT.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelMenus.setBackground(new java.awt.Color(0, 98, 175));
        jPanelMenus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 0, 204)));
        jPanelMenus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clientes.setBackground(new java.awt.Color(0, 98, 175));
        Clientes.setPreferredSize(new java.awt.Dimension(890, 100));
        Clientes.setRequestFocusEnabled(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Add User Male_30px.png"))); // NOI18N
        jLabel6.setText("Agregar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Edit User Male_30px_1.png"))); // NOI18N
        jLabel7.setText("Modificar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Remove User Male_30px.png"))); // NOI18N
        jLabel18.setText("Eliminar");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Ingredients List_30px.png"))); // NOI18N
        jLabel19.setText("Obtener lista Completa");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Find User Male_30px.png"))); // NOI18N
        jLabel20.setText("Buscar Usuario");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/toolBar/Filter_30px_1.png"))); // NOI18N
        jLabel21.setText("Obtener lista Filtrada");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelMenus.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RRHH.setBackground(new java.awt.Color(0, 98, 175));

        javax.swing.GroupLayout RRHHLayout = new javax.swing.GroupLayout(RRHH);
        RRHH.setLayout(RRHHLayout);
        RRHHLayout.setHorizontalGroup(
            RRHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        RRHHLayout.setVerticalGroup(
            RRHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(RRHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Inventario.setBackground(new java.awt.Color(0, 98, 175));
        Inventario.setPreferredSize(new java.awt.Dimension(890, 100));

        javax.swing.GroupLayout InventarioLayout = new javax.swing.GroupLayout(Inventario);
        Inventario.setLayout(InventarioLayout);
        InventarioLayout.setHorizontalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        InventarioLayout.setVerticalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Reservacion.setBackground(new java.awt.Color(0, 98, 175));
        Reservacion.setPreferredSize(new java.awt.Dimension(890, 100));

        javax.swing.GroupLayout ReservacionLayout = new javax.swing.GroupLayout(Reservacion);
        Reservacion.setLayout(ReservacionLayout);
        ReservacionLayout.setHorizontalGroup(
            ReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        ReservacionLayout.setVerticalGroup(
            ReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(Reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Historico.setBackground(new java.awt.Color(0, 98, 175));
        Historico.setPreferredSize(new java.awt.Dimension(890, 100));

        javax.swing.GroupLayout HistoricoLayout = new javax.swing.GroupLayout(Historico);
        Historico.setLayout(HistoricoLayout);
        HistoricoLayout.setHorizontalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        HistoricoLayout.setVerticalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(Historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Disponibilidad.setBackground(new java.awt.Color(0, 98, 175));
        Disponibilidad.setPreferredSize(new java.awt.Dimension(890, 100));

        javax.swing.GroupLayout DisponibilidadLayout = new javax.swing.GroupLayout(Disponibilidad);
        Disponibilidad.setLayout(DisponibilidadLayout);
        DisponibilidadLayout.setHorizontalGroup(
            DisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        DisponibilidadLayout.setVerticalGroup(
            DisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(Disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Session.setBackground(new java.awt.Color(0, 98, 175));
        Session.setPreferredSize(new java.awt.Dimension(890, 100));

        javax.swing.GroupLayout SessionLayout = new javax.swing.GroupLayout(Session);
        Session.setLayout(SessionLayout);
        SessionLayout.setHorizontalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        SessionLayout.setVerticalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelMenus.add(Session, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelClientes.setBackground(new java.awt.Color(1, 151, 190));
        jLabelClientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setText("Clientes");
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabelRRHH.setBackground(new java.awt.Color(1, 151, 190));
        jLabelRRHH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRRHH.setText("RRHH");
        jLabelRRHH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRRHHMouseClicked(evt);
            }
        });

        jLabelInventario.setBackground(new java.awt.Color(1, 151, 190));
        jLabelInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInventario.setText("Inventario");
        jLabelInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInventarioMouseClicked(evt);
            }
        });

        jLabelReservacion.setBackground(new java.awt.Color(1, 151, 190));
        jLabelReservacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReservacion.setText("Reservacion");
        jLabelReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservacionMouseClicked(evt);
            }
        });

        jLabelHistorico.setBackground(new java.awt.Color(1, 151, 190));
        jLabelHistorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHistorico.setText("Historico Cliente");
        jLabelHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHistoricoMouseClicked(evt);
            }
        });

        jLabelDisponibilidad.setBackground(new java.awt.Color(1, 151, 190));
        jLabelDisponibilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDisponibilidad.setText("Disponibilidad");
        jLabelDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDisponibilidadMouseClicked(evt);
            }
        });

        jLabelSession.setBackground(new java.awt.Color(1, 151, 190));
        jLabelSession.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSession.setText("Session");
        jLabelSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSessionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabelReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabelRRHH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSession, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelRRHH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDisponibilidad)
                        .addComponent(jLabelSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionesCliente.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesCliente.setPreferredSize(new java.awt.Dimension(0, 264));

        jLabel8.setText("Nombre:");

        jLabel9.setText("Primer Apellido:");

        jLabel10.setText("Segundo Apellido:");

        jLabel11.setText("Fecha de Nacimiento:");

        jLabel12.setText("Direccion:");

        jLabel13.setText("Profesion:");

        jLabel14.setText("Cedula:");

        jLabel15.setText("Carnet:");

        jLabel16.setText("Estado:");

        jLabel17.setText("Genero:");

        ClienteGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        ClienteGenero.setToolTipText("");

        ClienteEstado.setBackground(new java.awt.Color(255, 255, 255));
        ClienteEstado.setText("Activo");

        ClienteFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        ClienteFechaNacimiento.setText("31-12-1992");
        ClienteFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClienteFechaNacimientoKeyReleased(evt);
            }
        });

        ClienteEdad.setText("Fecha de Nacimiento:");

        javax.swing.GroupLayout OpcionesClienteLayout = new javax.swing.GroupLayout(OpcionesCliente);
        OpcionesCliente.setLayout(OpcionesClienteLayout);
        OpcionesClienteLayout.setHorizontalGroup(
            OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesClienteLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpcionesClienteLayout.createSequentialGroup()
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClientePrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(OpcionesClienteLayout.createSequentialGroup()
                                .addComponent(ClienteSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesClienteLayout.createSequentialGroup()
                                .addComponent(ClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel11))
                            .addGroup(OpcionesClienteLayout.createSequentialGroup()
                                .addComponent(ClienteProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(OpcionesClienteLayout.createSequentialGroup()
                                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClienteEdad))
                                .addGap(18, 18, 18)
                                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClienteEstado)))))
                    .addComponent(ClienteGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        OpcionesClienteLayout.setVerticalGroup(
            OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(ClienteCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(ClientePrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(ClienteEstado))
                    .addComponent(ClienteEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OpcionesClienteLayout.createSequentialGroup()
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ClienteSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ClienteProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OpcionesClienteLayout.createSequentialGroup()
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(ClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OpcionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ClienteGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel3.add(OpcionesCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        OpcionesRRHH.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesRRHH.setPreferredSize(new java.awt.Dimension(0, 264));

        javax.swing.GroupLayout OpcionesRRHHLayout = new javax.swing.GroupLayout(OpcionesRRHH);
        OpcionesRRHH.setLayout(OpcionesRRHHLayout);
        OpcionesRRHHLayout.setHorizontalGroup(
            OpcionesRRHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        OpcionesRRHHLayout.setVerticalGroup(
            OpcionesRRHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jPanel3.add(OpcionesRRHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        OpcionesInventario.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesInventario.setPreferredSize(new java.awt.Dimension(0, 264));

        javax.swing.GroupLayout OpcionesInventarioLayout = new javax.swing.GroupLayout(OpcionesInventario);
        OpcionesInventario.setLayout(OpcionesInventarioLayout);
        OpcionesInventarioLayout.setHorizontalGroup(
            OpcionesInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        OpcionesInventarioLayout.setVerticalGroup(
            OpcionesInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jPanel3.add(OpcionesInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        OpcionesReservacion.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesReservacion.setPreferredSize(new java.awt.Dimension(0, 264));

        javax.swing.GroupLayout OpcionesReservacionLayout = new javax.swing.GroupLayout(OpcionesReservacion);
        OpcionesReservacion.setLayout(OpcionesReservacionLayout);
        OpcionesReservacionLayout.setHorizontalGroup(
            OpcionesReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        OpcionesReservacionLayout.setVerticalGroup(
            OpcionesReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jPanel3.add(OpcionesReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        OpcionesHistorico.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesHistorico.setPreferredSize(new java.awt.Dimension(0, 264));

        javax.swing.GroupLayout OpcionesHistoricoLayout = new javax.swing.GroupLayout(OpcionesHistorico);
        OpcionesHistorico.setLayout(OpcionesHistoricoLayout);
        OpcionesHistoricoLayout.setHorizontalGroup(
            OpcionesHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        OpcionesHistoricoLayout.setVerticalGroup(
            OpcionesHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jPanel3.add(OpcionesHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        OpcionesDisponibilidad.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesDisponibilidad.setPreferredSize(new java.awt.Dimension(0, 264));

        javax.swing.GroupLayout OpcionesDisponibilidadLayout = new javax.swing.GroupLayout(OpcionesDisponibilidad);
        OpcionesDisponibilidad.setLayout(OpcionesDisponibilidadLayout);
        OpcionesDisponibilidadLayout.setHorizontalGroup(
            OpcionesDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        OpcionesDisponibilidadLayout.setVerticalGroup(
            OpcionesDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jPanel3.add(OpcionesDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 279));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSessionMouseClicked
        enabledHeader(jLabelSession);
        enabledPanels(Session, null, 0);
        getCurrentContentTable(6, false);
    }//GEN-LAST:event_jLabelSessionMouseClicked

    private void jLabelDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDisponibilidadMouseClicked
        enabledHeader(jLabelDisponibilidad);
        enabledPanels(Disponibilidad, OpcionesDisponibilidad, 5);
        getCurrentContentTable(5, false);
    }//GEN-LAST:event_jLabelDisponibilidadMouseClicked

    private void jLabelHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistoricoMouseClicked
        enabledHeader(jLabelHistorico);
        enabledPanels(Historico, OpcionesHistorico, 4);
        getCurrentContentTable(4, false);
    }//GEN-LAST:event_jLabelHistoricoMouseClicked

    private void jLabelReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservacionMouseClicked
        enabledHeader(jLabelReservacion);
        enabledPanels(Reservacion, OpcionesReservacion, 3);
        getCurrentContentTable(3, false);
    }//GEN-LAST:event_jLabelReservacionMouseClicked

    private void jLabelInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInventarioMouseClicked
        enabledHeader(jLabelInventario);
        enabledPanels(Inventario, OpcionesInventario, 2);
        getCurrentContentTable(2, false);
    }//GEN-LAST:event_jLabelInventarioMouseClicked

    private void jLabelRRHHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRRHHMouseClicked
        enabledHeader(jLabelRRHH);
        enabledPanels(RRHH, OpcionesRRHH, 1);
        getCurrentContentTable(1, false);
    }//GEN-LAST:event_jLabelRRHHMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        enabledHeader(jLabelClientes);
        enabledPanels(Clientes, OpcionesCliente, 0);
        getCurrentContentTable(0, false);
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        setCurrentLocation(evt);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if (evt.getClickCount() == 2) {
            if (normalSize) {
                this.setExtendedState(MAXIMIZED_BOTH);
                normalSize = false;
            } else {
                this.setExtendedState(NORMAL);
                normalSize = true;
            }
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Mover(evt);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/CANCEL-GRANDE-OUT.png"))); // NOI18N
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/CANCEL-GRANDE-IN.png"))); // NOI18N
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(-1);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MIN-40-OUT.png"))); // NOI18N
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MIN-40-IN.png"))); // NOI18N
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        if (normalSize) {
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MAXIN-40-OUT.png"))); // NOI18N
        } else {
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/REST-GRANDE-OUT.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        if (normalSize) {
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/MAXIN-40-IN.png"))); // NOI18N
        } else {
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/res/icons/BOTONERA GRANDE/REST-GRANDE-IN.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (normalSize) {
            this.setExtendedState(MAXIMIZED_BOTH);
            normalSize = false;
        } else {
            this.setExtendedState(NORMAL);
            normalSize = true;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        getCurrentContentTable(0, false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        getCurrentContentTable(0, true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if ("".equals(ClienteCarnet.getText())
                || "".equals(ClienteCedula.getText())
                || "".equals(ClienteDireccion.getText())
                || "".equals(ClienteFechaNacimiento.getText())
                || "".equals(ClienteNombre.getText())
                || "".equals(ClientePrimerApellido.getText())
                || "".equals(ClienteSegundoApellido.getText())
                || "".equals(ClienteProfesion.getText())) {
            JOptionPane.showMessageDialog(this, "Debe de rellenar todos los campos para poder hacer la inserción");
        } else {
            jTable1.setModel(new ClientesBL().addCliente(new Entidades.Cliente(ClienteNombre.getText(), ClientePrimerApellido.getText(), ClienteSegundoApellido.getText(), ClienteFechaNacimiento.getText(), ClienteDireccion.getText(), ClienteProfesion.getText(), String.valueOf(ClienteGenero.getSelectedItem()), Integer.parseInt(ClienteCedula.getText()), Integer.parseInt(ClienteCarnet.getText()), ClienteEstado.isSelected())));

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ClienteFechaNacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteFechaNacimientoKeyReleased
        try {
            if (ClienteFechaNacimiento.getText().length() == 10) {
                java.util.Date fechaActual = new java.util.Date();
                java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd-MM-yyyy");
                String hoy = formato.format(fechaActual);
                String[] dat1 = ClienteFechaNacimiento.getText().split("-");
                String[] dat2 = hoy.split("-");
                int anos = Integer.parseInt(dat2[2]) - Integer.parseInt(dat1[2]);
                int mes = Integer.parseInt(dat2[1]) - Integer.parseInt(dat1[1]);
                if (mes < 0) {
                    anos = anos - 1;
                } else if (mes == 0) {
                    int dia = Integer.parseInt(dat2[0]) - Integer.parseInt(dat1[0]);
                    if (dia > 0) {
                        anos = anos - 1;
                    }
                }
                if (anos > 18) {
                    ClienteEdad.setText("Tienes " + String.valueOf(anos) + " años, eres mayor de edad");
                } else {
                    ClienteEdad.setText("Tienes " + String.valueOf(anos) + " años, eres menor de edad");
                }
            } else {
                ClienteEdad.setText("Formato no valido");
            }
        } catch (Exception e) {
            ClienteEdad.setText("Formato no valido");
        }
    }//GEN-LAST:event_ClienteFechaNacimientoKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        switch (this.TableActive) {
            case 0:
                ClienteNombre.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0)));
                ClientePrimerApellido.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1)));
                ClienteSegundoApellido.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)));
                ClienteFechaNacimiento.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3)));
                ClienteDireccion.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4)));
                ClienteProfesion.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5)));
                ClienteGenero.setSelectedIndex(0);
//                ClienteCedula.getText()
//                ClienteCarnet.getText()
//                ClienteEstado.isSelected();
                break;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        switch (this.TableActive) {
            case 0:
                jTable1.setModel(new ClientesBL().editItem(new Entidades.Cliente(ClienteNombre.getText(), ClientePrimerApellido.getText(), ClienteSegundoApellido.getText(), ClienteFechaNacimiento.getText(), ClienteDireccion.getText(), ClienteProfesion.getText(), String.valueOf(ClienteGenero.getSelectedItem()), Integer.parseInt(ClienteCedula.getText()), Integer.parseInt(ClienteCarnet.getText()), ClienteEstado.isSelected()), Integer.parseInt(ClienteCedula.getText())));
                break;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        switch (this.TableActive) {
            case 0:
                jTable1.setModel(new ClientesBL().deleteItem(Integer.parseInt(ClienteCedula.getText())));
                break;
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void setCurrentLocation(MouseEvent evt) {
        x = evt.getX();
        y = evt.getY();
    }

    private void Mover(java.awt.event.MouseEvent evt) {
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }

    private void enabledHeader(javax.swing.JLabel enabled) {
        javax.swing.JLabel[] disabled = new javax.swing.JLabel[]{jLabelClientes, jLabelRRHH, jLabelInventario, jLabelReservacion, jLabelHistorico, jLabelDisponibilidad, jLabelSession,};
        for (JLabel Label : disabled) {
            if (Label == enabled) {
                Label.setForeground(new java.awt.Color(255, 255, 255));
                Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            } else {

                Label.setForeground(new java.awt.Color(0, 0, 0));
                Label.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
            }
        }
    }

    private void enabledPanels(javax.swing.JPanel Riboon, javax.swing.JPanel Controls, int TableActive) {
        javax.swing.JPanel[] RiboonP = new javax.swing.JPanel[]{Clientes, Disponibilidad, Historico, Inventario, RRHH, Reservacion, Session};
        for (JPanel Panele : RiboonP) {
            if (Panele == Riboon) {
                Panele.setVisible(true);
            } else {
                Panele.setVisible(false);
            }
        }
        javax.swing.JPanel[] ControlsP = new javax.swing.JPanel[]{OpcionesCliente, OpcionesDisponibilidad, OpcionesHistorico, OpcionesInventario, OpcionesRRHH, OpcionesReservacion};
        for (JPanel Contol : ControlsP) {
            if (Contol == Controls) {
                Contol.setVisible(true);
            } else {
                Contol.setVisible(false);
            }
        }

        this.TableActive = TableActive;
    }

    private void getCurrentContentTable(int i, boolean filtrado) {
        switch (i) {
            case 0:
                jTable1.setModel(new ClientesBL().getModelDataTable(filtrado));
                break;
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClienteCarnet;
    private javax.swing.JTextField ClienteCedula;
    private javax.swing.JTextField ClienteDireccion;
    private javax.swing.JLabel ClienteEdad;
    private javax.swing.JCheckBox ClienteEstado;
    private javax.swing.JFormattedTextField ClienteFechaNacimiento;
    private javax.swing.JComboBox ClienteGenero;
    private javax.swing.JTextField ClienteNombre;
    private javax.swing.JTextField ClientePrimerApellido;
    private javax.swing.JTextField ClienteProfesion;
    private javax.swing.JTextField ClienteSegundoApellido;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Disponibilidad;
    private javax.swing.JPanel Historico;
    private javax.swing.JPanel Inventario;
    private javax.swing.JPanel OpcionesCliente;
    private javax.swing.JPanel OpcionesDisponibilidad;
    private javax.swing.JPanel OpcionesHistorico;
    private javax.swing.JPanel OpcionesInventario;
    private javax.swing.JPanel OpcionesRRHH;
    private javax.swing.JPanel OpcionesReservacion;
    private javax.swing.JPanel RRHH;
    private javax.swing.JPanel Reservacion;
    private javax.swing.JPanel Session;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDisponibilidad;
    private javax.swing.JLabel jLabelHistorico;
    private javax.swing.JLabel jLabelInventario;
    private javax.swing.JLabel jLabelRRHH;
    private javax.swing.JLabel jLabelReservacion;
    private javax.swing.JLabel jLabelSession;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMenus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
